Header header

# Holds stopsign elements
SpatioTemporalNode[] stops 

# Holds crossings
SpatioTemporalNode[] crossings 

# Holds signals
SpatioTemporalNode[] signals 

# Holds waypoints of traversed path [W0...W_pose] 
SpatioTemporalNode[] traversed_path 

# Holds waypoints of planned path [W_pose+1...W_dest]
SpatioTemporalNode[] planned_path 

# Adjacency list corresponding to road network
SpatioTemporalNode[] road_network 



 

